# sonar-project.properties
sonar.organization=andrewkant-ml
sonar.projectKey=cantarell-light-12pt_ISW2_2526
sonar.host.url=https://sonarcloud.io

# Source encoding
sonar.sourceEncoding=UTF-8

# Specify the paths to your source directories
sonar.sources=src

# Specify the path to your compiled classes (Add this line)
sonar.java.binaries=target/classes