# sonar-project.properties
sonar.organization=andrewkant-ml
sonar.projectKey=cantarell-light-12pt_ISW2_2526
sonar.host.url=https://sonarcloud.io

# Source encoding
sonar.sourceEncoding=UTF-8

# Specify the paths to your source directories (adjust based on project architecture)
sonar.sources=src